prettyPrint: true
cacheTTL: 0
openAPI:
  info:
    version: '1.0.0'
    title: 'Test BACK END'
  servers:
    - url: '/api'
components:
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: [] 